language: java
script: mvn clean verify
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
   - oraclejdk8

after_success:
  - test -e target/site/jacoco/jacoco.xml || echo "Code coverage failed"
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  slack:
    secure: wWe3yoybC5CmMcpyFCkbGnr2C/fvuXXpDpp8p894PwECxNzwiAgVgAUJRuZIkiCxyHllXHfKlW7ZBWLegn+FwV4LcCCj4Gs+SfRT0+0vInSOpbmbUQsChIgufcLRlsByEzyRG4zyeWOp34LJ7aPpjOiMM6oF7zC8kF5DT/wjqpxQs+ToiWqLcmhCsMimnWJ5yVNa8KJP33OGGQQYnVWYglY5EqIW4HR/Lnd99GkU4RD1oLbioXRY3i3lv/7bVJBRFyLdoJ/DIObzCPjd+uCjT1LhGc2dOlVtdtccPnzlqHypYhmJrqJumf1JtSzu0X5UHZNVv2KNjPzv169kMertFF2eIk6DfItprTMQIQokTf5SSjwArBr3RrII3eaJU+b91piUBtLAJYUfsZCHhzJXe2QfZGzDNLNv/OfC5gzLubXJTUa0rzenoZf/1MpliQ25HiV6rzK4X1pwySTW5HCiygapw3o/W5K32hFWYpTZkGnwevMhM75iah/Of4rpJHgT44vq5DM0LPh9FlZwk2Re02ZosMpnAmwxEsl8pOVE91+Fipcj7fn3gboRQov5fHjIOCDzSQscR/b8XWa+kJaR19iklddCePAaWe1pRZWnconuOjwQemuEnfD4Dxj3oA/8mTIp62UiijjCpH6DmEpefpnTBRffVajC/LIAOAQx2bw=
